openapi: 3.0.3
info:
  version: '1.0.0'
  title: Stocks API
  description: Stocks API for fun
  contact:
    name: NIG
    email: nig@myself.com

servers:
  - url: https://localhost:8080
paths:
  /stocks:
    $ref: './components/endpoints/Stocks.yml'

