/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nig.stocks.application.codegen

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nig.stocks.application.codegen.StockApi

class StockApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StockApi
        //val apiInstance = StockApi()

        // to test getStocks
        should("test getStocks") {
            // uncomment below to test getStocks
            //val size : java.math.BigDecimal = 8.14 // java.math.BigDecimal | Size.
            //val result : kotlin.Any = apiInstance.getStocks(size)
            //result shouldBe ("TODO")
        }

    }
}
